export enum Lang {
  English = 'English',
  Chinese = 'Chinese',
  Japanese = 'Japanese',
  Korean = 'Korean',
  French = 'French',
  German = 'German',
  Spanish = 'Spanish',
  Italian = 'Italian',
  Indian = 'Indian',
  Filipino = 'Filipino',
  Russian = 'Russian',
  Portuguese = 'Portuguese',
  Dutch = 'Dutch',
  Swedish = 'Swedish',
  Danish = 'Danish',
  Norwegian = 'Norwegian',
  Finnish = 'Finnish',
  Polish = 'Polish',
  Czech = 'Czech',
  Hungarian = 'Hungarian',
  Romanian = 'Romanian',
  Turkish = 'Turkish',
  Greek = 'Greek',
  Bulgarian = 'Bulgarian',
  Arabic = 'Arabic',
  Hebrew = 'Hebrew',
  Hindi = 'Hindi',
}

export enum Interpreter {
  JS_V8 = 'NodeJS',
}
